services:
  janus-gateway:
    image: sucwangsr/janus-webrtc-gateway-docker:1.2.1-arm64
    network_mode: host
    volumes:
      - ~/janus-conf:/usr/local/etc/janus
    container_name: janus-gateway
    restart: unless-stopped
    environment:
      - G_SLICE=always-malloc