version: '3.8'

services:
  janus:
    image: canyan/janus-gateway:latest
    network_mode: host
    volumes:
      - /home/ubuntu/janus-config:/usr/local/etc/janus
      - /home/ubuntu/janus-certs:/usr/local/share/janus/certs
    container_name: janus
    restart: unless-stopped